### ISSUE TITLE
Add option turn off auto generates files

### ISSUE THREAD

**Issue by 3xploiton3** [CaffeineOnIce/AutoMinify#10]
Automatically generates a .min.html, .min.css, or .min.js file each time you save a .html, .css, or .js file.
For example: styles.css becomes styles.min.css.

**Comment by CaffeineOnIce** [comment]
I mean, do you actually need such option? Just disable the extension, I guess?

**Comment by 3xploiton3** [comment]
you right, forget this feature, thanks
