### ISSUE TITLE
2 ideas that I think would be very useful

### ISSUE THREAD

**Issue by TalkNetApps** [CaffeineOnIce/AutoMinify#2]
Hello, excellent extension! I would like to propose 2 ideas that I think would be very useful: 1. You can configure to create a separate folder for the entire project (project.min/index.min.html - project.min/js/functions.min.js- ... ), with the same file structure, so that the entire minified project can be uploaded to the server? and 2. Can an obfuscate function be added before minifying? Thank you very much for the extension and it would be great to be able to add these 2 features.

**Comment by CaffeineOnIce** [comment]
Ah. A seperate folder for the min files eh? That might be possible. I'll add it to my notes.

And for the obsfurcation, I don't understand. You mean mangling? For JS, you can enable the mangling by adding the mangling option in the settings.json for terser. For HTML and CSS, I won't recommend mangling, as they're not exactly useful.

**Comment by TalkNetApps** [comment]
The problem of speaking different languages, I don't quite understand what mangling is, but I'll leave you a link to what I mean by obfuscation: https://js.jscrambler.com/protect-javascript

**Comment by CaffeineOnIce** [comment]
ah, an obsfurcator eh? I'll add in the notes. But, if terser doesn't support it, I'll need to work out something else or probably, write natively without APIs. I'll look upon it.

**Comment by CaffeineOnIce** [comment]
@TalkNetApps Obsfurcator option will be hard to implement. Given the fact that terser doesn't have an obsfurcation option. I can implement https://obfuscator.io/ api and make it so, but there's way to many factors in play here. Terser and obsfurcator API are conflicting. So it'll be hard to implement it. It's currently on hold. I'll think about it later.

For the seperate folder, I've implemented a boolean checkbox in the settings. It'll create a seperate folder called 'min' where the min files will be pasted.

Will push out in next update.
