### ISSUE TITLE
One more suggestion:

### ISSUE THREAD

**Issue by TalkNetApps** [CaffeineOnIce/AutoMinify#3]
When processing index.html you could replace the path of .js" .css" references with .min.js" and .min.css" (eg: <script src="main.js">< /script> for <script src="main.min.js"></script> and <link rel="stylesheet" href="style.css"> for <link rel="stylesheet" href="style.min .css"> ) When it's just these files, it's not a problem to do it by hand, but when it's multiple dependencies, it gets complicated. Also, either you have to modify the min file, or modify the original index, which would stop working.

**Comment by CaffeineOnIce** [comment]
Well, I largely intended the extension in the way, such that you'd edit the main files, and the changes will be in min files (given the fact that the css, html and js files are joined by ".min" extensions.

I'll do an update by the end of next month.

**Comment by CaffeineOnIce** [comment]
I have implemented a separate folder toggle for storing the min files. I think it should bypass your issue, I can't implement the code to change the main.js file to main.min.js, due to various security issues and conflicting codes. Until then, this should suffice.
