### ISSUE TITLE
One more suggestion

### ISSUE THREAD

**Issue by TalkNetApps** [CaffeineOnIce/AutoMinify#4]
When minifying, remove all console.log. Another rather tedious manual task

**Comment by CaffeineOnIce** [comment]
Any particular reasons why I should make such change? I'm not being rude, I just wanna know the reasons. I'm listing down all the notes.

**Comment by TalkNetApps** [comment]
No problem, at no time would I think you're rude. Anything that avoids manual processes is useful to me, and when I go to minify a file, it is to publish it, for which I have to delete all the console.log that I used for debugging, (not the console.error, warn , etc, those if they remain). Obviously I propose these ideas as optional configurations, they would be extremely useful to me, perhaps not to others. But if the same extension that minifies it for me creates the same file and folder structure in another folder (which I choose) with the minified files ready to upload, it obfuscates it to make reverse engineering difficult, it adapts the .min paths for me. and it deletes my console.log, since that is an extension on steroids. By the way, it would also be nice to allow exceptions, ie files that should not be minified, like sw.js or manifest.json. The configuration could simply be done in a json file in the project folder (as in SFTP, another extension that helps me a lot in process automation). I hope this explanation is useful to you, you can ask all the questions you need, I found your extension looking for another one that I saw in a short, and it seemed much better to me, and if I can contribute to improving it, it also works for me. Thanks for responding and for your time.

**Comment by CaffeineOnIce** [comment]
Ah, I understand. I'll add some texr box or something to delist the files from being formatted by using filename.
 I'll provide an option to delete the console logs too. I've taken notes of your previous suggestions.

This is my first extension too, so I need to ckean up the code anyway. I'll do a major update, say, in a week :)

**Comment by CaffeineOnIce** [comment]
@TalkNetApps I tried to implement that. Just check if it works, else, I'll fix it in next minor update.
