### ISSUE TITLE
Can you please add source-map to JS-minify

### ISSUE THREAD

**Issue by virik** [CaffeineOnIce/AutoMinify#5]
Seems the terser option doesn't quite work as they should? :)

**Comment by CaffeineOnIce** [comment]
I'll check on it, mate. I don't know why it won't work, tho. I'll check terser options again.

**Comment by CaffeineOnIce** [comment]
I've implemented it. Will push out in next update.

**Comment by virik** [comment]
Any update here yet? :) 

And will you fix support for the other terser options?
Like "toplevel: true" to compress and/or mangle variables in top level scope.

**Comment by CaffeineOnIce** [comment]
Source maps is added though? Just check the box in the extension settings for source maps. It'll create a '.map' file in the same parent folder.

And I think other terser and other extension options work though? Can you double check?

**Comment by CaffeineOnIce** [comment]
And btw, Source maps option is added. Just check the box in the extension settings for source maps. It'll create a '.map' file in the same parent folder.

**Comment by virik** [comment]
Hi again. Source maps works great now thanks. 

I cannot get terser options to work though. Maybe I'm doing it wrong. I'm trying to get the @import file to be included in the app.min.js (https://d.pr/i/52v0ga). I support mangle toplevel does this, but I'm not quite sure. Nothing happens when I try this at least: https://d.pr/i/gMZl2c.

**Comment by CaffeineOnIce** [comment]
Uh, I don't mean to be rude, but I don't think that's how mangling works. Mangling changes long variable names to short ones. And for the @import code, the whole line is a string of keywords. None of it, is a variable. Mangling in terser checks for variables. Not keywords.

Also, that, mangling for high level code may change stuff up, so, I wouldn't recommend.
But as you've said that it doesn't work, I'll look into it.

In the mean time, I'd say, just go through the terser docs for mangling options. I myself, do not use mangling. Also, you've have to enable mangle-properties.

I'd recommend going through terser options.

**Comment by virik** [comment]
Thanks for clarifying. Do you know if it's possible to achieve what I'm after? I know the app Prepros compiles the imported file, but it would be great if your app did the same :)

**Comment by CaffeineOnIce** [comment]
can you just explain what actually you want to achieve? You want mangling? or do you want to remove spaces in that line? what exactly do you want?

**Comment by CaffeineOnIce** [comment]
ah. From the looks of it, I presume Prepros includes a a Preprocessor? I assume it imports the .carousel/.. file and unravels it. 

Sorry mate, the minifer I made doesn't do that. Not that I can't make it so, but that, it isn't a Preprocessor. It literally isn't in its scope of working. It's literally a separate working.

The primary reason mine cannot do it, is that, Prepos already has the necessary syntax and semantics to convert scss, or less files, and convert it's syntaxes and semantics into native css. Mine just minifies. I didn't intend to compile scss or less to native css.

Sorry, mate. I might one day make one extension including compilation and minifier too, but that's a thought for another day.
