### ISSUE TITLE
Removes necessary spaces between links and text

### ISSUE THREAD

**Issue by Andrey-Da-Actor** [CaffeineOnIce/AutoMinify#6]
Hi!
Auto-minify removes necessary spaces before and after links and text.
What settings are responsible for this or is this a bug?
Like:
some text<a href....
...</a>some other text

**Comment by CaffeineOnIce** [comment]
Can you explain in a bit more detail? I'm sorry, but I don't understand what you're saying.

**Comment by Andrey-Da-Actor** [comment]
Thx for lightning fast reply!
Sure
The minifier removes spaces between text and hyperlink in paragraph which are actually needed.
in original html it looks like:
someText someLink someText

after minifying it is without spaces like:
someTextsomeLinksomeText
but the spaces between hyperlink and plain text are intended and should stay...

**Comment by Andrey-Da-Actor** [comment]
Did one by one as you said, but unfortunately did not help.
{
    "vscodeGoogleTranslate.preferredLanguage": "Hebrew",
    "MinifyAll.minifyOnSaveToNewFile": true,
    "MinifyAll.openMinifiedDocument": false,
    "autominify.htmlminifier": {
        "caseSensitive": true,
        "collapseWhitespace": false,
        "collapseInlineTagWhitespace": false,
        "continueOnParseError": true,
        "removeComments": true,
        "removeAttributeQuotes": true,
        "minifyCSS": true,
        "minifyJS": true
    },
    "autominify.cleancss": {
        


        "level": {
            "1": {
                "all": true
            }
        }
    }
}
P.S. Do you mean exiting and running vscode again by restarting?

**Comment by CaffeineOnIce** [comment]
> P.S. Do you mean exiting and running vscode again by restarting?

yeah, or do F1 and type reload and enter

**Comment by CaffeineOnIce** [comment]
I'm still pretty sure there shouldn't be any problems due to that, unless there's inline formatting.
Maybe there is another html-minifier option I don't know about.

**Comment by Andrey-Da-Actor** [comment]
Just to be sure, I deleted other extension, despite the fact that it has nothing to do with this issue, unfortunately of course that didn't help either.

Here's the fragment of html, affected by minification:

<p>For visiting<a target=_blank href=https://superstar.actor>my official website</a>. I am a passionate Actor with years of experience in the industry. I love what I do, and want others<a href=#headshots>to see</a>, that Love shine through in all of my work (including<a target=_blank href=https://superstar.actor>this website</a>&nbsp;itself). Take a look around to find more information about myself, my career, updates on projects I’m working on, important<a href=#news>news</a>&nbsp;and other upcoming events...</p>

Can you see there are no spaces between plain text and hyperlink. Before the link but not after. Probably it is somehow related to how minifier processes spaces followed by <a href= sequence...

P.S. how to put screenshots here?

**Comment by CaffeineOnIce** [comment]
that's weird. I'll look into it by tomorrow and will inform you if it can be fixed.

btw, you can insert screenshot from the small image icon over the textbox.

**Comment by CaffeineOnIce** [comment]
I have checked over the code, but I couldn't find any problems in it. I'll update the extension when any dependency update comes out. I'll still check for the problems. Until then, I'm closing this issue. You can reopen the thread in next update.
