### ISSUE TITLE
Add as Optional: Open file after minify it

### ISSUE THREAD

**Issue by 3xploiton3** [CaffeineOnIce/AutoMinify#9]
can you make after minify it, it will open file at next tab?

![image](https://github.com/CaffeineOnIce/AutoMinify/assets/19517680/28ebeac8-15e8-405b-812e-c77470b36111)

**Comment by CaffeineOnIce** [comment]
Can do, but VSCode documented API is utterly messy. Will have to search for such triggers.
But, also, I'll probably update on 16th Dec, due to me having exams currently.

**Comment by 3xploiton3** [comment]
* The minified code will be displayed in a new slide. 
* without having save file

**Comment by CaffeineOnIce** [comment]
I don't understand. Can you explain a bit?

**Comment by CaffeineOnIce** [comment]
aha, a review pane, eh? Well, I have many things marked for the update, so this will take more time to build. Might not be in the next update. 
Might be in another update after the 16th one before  31st December. I'll see to it.

**Comment by CaffeineOnIce** [comment]
@3xploiton3 I've implemented it. Will push out the update in a few days.
